// Generated by scripts/build-plugin-ui.mjs. The checked-in fallback keeps tests and development startup deterministic before the build step runs.
export const SPORTFOLIO_WIDGET_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="color-scheme" content="light dark" />
    <title>Sportfolio</title>
    <style>
      body { margin: 0; font: 14px system-ui, sans-serif; color: CanvasText; background: transparent; }
      main { margin: 8px; padding: 16px; border: 1px solid color-mix(in srgb, CanvasText 18%, transparent); border-radius: 16px; background: Canvas; }
    </style>
  </head>
  <body>
    <main>Sportfolio UI assets are ready to build. Run <code>npm run plugin:ui:build</code>.</main>
  </body>
</html>`;
