// Generated by scripts/build-plugin-ui.mjs. Do not edit directly.
// This checked-in fallback keeps source-level audits and protocol smoke import-safe.
// Production and CI builds replace it with the exact content-addressed asset path.
export const SPORTFOLIO_WIDGET_ASSET_ORIGIN_PLACEHOLDER = "__SPORTFOLIO_ASSET_ORIGIN__";
export const SPORTFOLIO_WIDGET_HTML_TEMPLATE = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover" />
    <meta name="color-scheme" content="light dark" />
    <title>Sportfolio</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="${SPORTFOLIO_WIDGET_ASSET_ORIGIN_PLACEHOLDER}/assets/plugin-ui/sportfolio-widget.js"></script>
  </body>
</html>`;

export function buildSportfolioWidgetHtml(assetOrigin = "https://www.sportfolio.market") {
  const normalizedOrigin = assetOrigin.replace(/\/+$/, "");
  return SPORTFOLIO_WIDGET_HTML_TEMPLATE.replaceAll(
    SPORTFOLIO_WIDGET_ASSET_ORIGIN_PLACEHOLDER,
    normalizedOrigin,
  );
}

export const SPORTFOLIO_WIDGET_HTML = buildSportfolioWidgetHtml();
