// Generated by scripts/build-plugin-ui.mjs. Do not edit directly.
export const SPORTFOLIO_WIDGET_ASSET_ORIGIN_PLACEHOLDER = "__SPORTFOLIO_ASSET_ORIGIN__";
export const SPORTFOLIO_WIDGET_HTML_TEMPLATE = "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\" />\n    <meta name=\"color-scheme\" content=\"light dark\" />\n    <title>Sportfolio</title>\n    \n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <script type=\"module\" src=\"__SPORTFOLIO_ASSET_ORIGIN__/assets/plugin-ui/sportfolio-widget-TLNE3RCK.js\"></script>\n  </body>\n</html>";
export function buildSportfolioWidgetHtml(assetOrigin = "https://www.sportfolio.market") {
  const normalizedOrigin = assetOrigin.replace(/\/+$/, "");
  return SPORTFOLIO_WIDGET_HTML_TEMPLATE.replaceAll(SPORTFOLIO_WIDGET_ASSET_ORIGIN_PLACEHOLDER, normalizedOrigin);
}
export const SPORTFOLIO_WIDGET_HTML = buildSportfolioWidgetHtml();
