import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { extname, relative, resolve } from "node:path";

export type SupabaseInventoryCategory =
  | "client-auth"
  | "server-auth"
  | "oauth-mcp"
  | "account-lifecycle"
  | "native"
  | "database-security"
  | "tests"
  | "scripts"
  | "documentation"
  | "configuration"
  | "package"
  | "historical-attachment";

export type SupabaseInventoryEntry = {
  path: string;
  category: SupabaseInventoryCategory;
  markers: string[];
};

const ROOT = resolve(import.meta.dirname, "..");
const TEXT_EXTENSIONS = new Set([
  ".cjs",
  ".js",
  ".json",
  ".md",
  ".mjs",
  ".sql",
  ".ts",
  ".tsx",
  ".txt",
  ".yaml",
  ".yml",
]);
const EXCLUDED_DIRS = new Set([".git", ".husky", "coverage", "dist", "node_modules", "tmp"]);
const MARKERS = [
  "@supabase/supabase-js",
  "SUPABASE_",
  "supabase.co",
  "supabase.auth",
  "supabaseAdmin",
  "supabaseClient",
  "supabaseAuth",
  "Supabase",
];

function walk(directory: string): string[] {
  const files: string[] = [];
  for (const name of readdirSync(directory)) {
    if (EXCLUDED_DIRS.has(name)) continue;
    const absolute = resolve(directory, name);
    const stat = statSync(absolute);
    if (stat.isDirectory()) files.push(...walk(absolute));
    else if (TEXT_EXTENSIONS.has(extname(name)) || name === ".env.example") files.push(absolute);
  }
  return files;
}

export function classifySupabasePath(path: string): SupabaseInventoryCategory | null {
  if (path === "package.json" || path === "package-lock.json") return "package";
  if (path === ".env.example" || path.startsWith(".github/") || path.startsWith(".claude/")) {
    return "configuration";
  }
  if (path.startsWith("attached_assets/")) return "historical-attachment";
  if (
    path.startsWith("migrations/") ||
    path.startsWith("docs/security/") ||
    path.includes("/supabase/")
  ) {
    return "database-security";
  }
  if (
    path.startsWith("docs/") ||
    path === "AGENTS.md" ||
    path.startsWith("tasks/") ||
    (!path.includes("/") && path.endsWith(".md"))
  ) {
    return "documentation";
  }
  if (path.startsWith("mobile/")) return "native";
  if (path.startsWith("tests/") || path.endsWith(".test.ts") || path.endsWith(".spec.ts")) {
    return "tests";
  }
  if (path.startsWith("scripts/")) {
    if (path.includes("oauth") || path.includes("plugin")) return "oauth-mcp";
    return "scripts";
  }
  if (path.startsWith("client/")) return "client-auth";
  if (path.includes("account-deletion")) return "account-lifecycle";
  if (path.startsWith("server/")) {
    if (path.includes("plugin") || path.includes("oauth") || path.includes("mcp"))
      return "oauth-mcp";
    return "server-auth";
  }
  return null;
}

export function collectSupabaseInventory(root = ROOT): {
  entries: SupabaseInventoryEntry[];
  unclassified: string[];
} {
  const entries: SupabaseInventoryEntry[] = [];
  const unclassified: string[] = [];
  for (const absolute of walk(root)) {
    const path = relative(root, absolute).replaceAll("\\", "/");
    const content = readFileSync(absolute, "utf8");
    const markers = MARKERS.filter((marker) => content.includes(marker));
    if (markers.length === 0) continue;
    const category = classifySupabasePath(path);
    if (!category) unclassified.push(path);
    else entries.push({ path, category, markers });
  }
  entries.sort((a, b) => a.path.localeCompare(b.path));
  unclassified.sort();
  return { entries, unclassified };
}

export function renderSupabaseInventory(entries: SupabaseInventoryEntry[]): string {
  const counts = new Map<SupabaseInventoryCategory, number>();
  for (const entry of entries) counts.set(entry.category, (counts.get(entry.category) ?? 0) + 1);
  const rows = entries
    .map((entry) => `| \`${entry.path}\` | ${entry.category} | ${entry.markers.join(", ")} |`)
    .join("\n");
  const summary = [...counts.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([category, count]) => `- ${category}: ${count}`)
    .join("\n");
  return `# Supabase exit inventory

Generated by \`npm run auth:supabase-inventory\`. Do not edit the generated table manually.

## Classification summary

${summary}

## Referenced files

| Path | Category | Detected markers |
| --- | --- | --- |
${rows}

## Interpretation

This is a historical source-dependency inventory used to verify the completed authentication migration. Railway Postgres is authoritative for Sportfolio application and authentication data. Active runtime authentication is Better Auth with Resend passwordless delivery; remaining Supabase references are migration, audit, documentation, or historical artifacts and must not be imported by active runtime code.
`;
}

export function runInventory(args = process.argv.slice(2)): void {
  const { entries, unclassified } = collectSupabaseInventory();
  if (unclassified.length > 0) {
    throw new Error(`Unclassified Supabase references:\n${unclassified.join("\n")}`);
  }
  const report = renderSupabaseInventory(entries);
  const outputIndex = args.indexOf("--write");
  if (outputIndex >= 0) {
    const output = args[outputIndex + 1] ?? "docs/auth/supabase-exit-inventory.md";
    writeFileSync(resolve(ROOT, output), report, "utf8");
  } else {
    process.stdout.write(report);
  }
}

const invoked = process.argv[1] ? resolve(process.argv[1]) : "";
if (invoked === resolve(import.meta.filename)) runInventory();
