export type GameplayCapabilityKind = "tool" | "resource" | "prompt" | "excluded";

export type GameplayCapabilityStatus = "included" | "excluded";

export type GameplayCapabilityEntry = {
  capabilityId: string;
  kind: GameplayCapabilityKind;
  status: GameplayCapabilityStatus;
  domain: string;
  toolName?: string;
  promptName?: string;
  resourceUri?: string;
  source: string;
  notes?: string;
};

export const INCLUDED_GAMEPLAY_CAPABILITIES: GameplayCapabilityEntry[] = [
  {
    capabilityId: "review_setup",
    kind: "tool",
    status: "included",
    domain: "advisory",
    toolName: "review_setup",
    source: "planner:broad_operator_review",
  },
  {
    capabilityId: "review_idle_cash",
    kind: "tool",
    status: "included",
    domain: "advisory",
    toolName: "review_idle_cash",
    source: "scan:scan_idle_balance_options",
  },
  {
    capabilityId: "review_portfolio_cleanup",
    kind: "tool",
    status: "included",
    domain: "advisory",
    toolName: "review_portfolio_cleanup",
    source: "scan:scan_portfolio_cleanup_levers",
  },
  {
    capabilityId: "list_boost_candidates",
    kind: "tool",
    status: "included",
    domain: "boosts",
    toolName: "list_boost_candidates",
    source: "scan:scan_daily_boost_candidates",
  },
  {
    capabilityId: "list_scout_opportunities",
    kind: "tool",
    status: "included",
    domain: "scouting",
    toolName: "list_scout_opportunities",
    source: "scan:scan_scout_opportunities",
  },
  {
    capabilityId: "list_market_opportunities",
    kind: "tool",
    status: "included",
    domain: "market",
    toolName: "list_market_opportunities",
    source: "scan:scan_top_market_opportunities",
  },
  {
    capabilityId: "review_news_impact",
    kind: "tool",
    status: "included",
    domain: "research",
    toolName: "review_news_impact",
    source: "scan:scan_news_impact",
  },
  {
    capabilityId: "get_dashboard_overview",
    kind: "tool",
    status: "included",
    domain: "dashboard",
    toolName: "get_dashboard_overview",
    source: "composed:dashboard_overview",
  },
  {
    capabilityId: "get_balance_state",
    kind: "tool",
    status: "included",
    domain: "account",
    toolName: "get_balance_state",
    source: "read:get_balance_state",
  },
  {
    capabilityId: "get_portfolio_summary",
    kind: "tool",
    status: "included",
    domain: "portfolio",
    toolName: "get_portfolio_summary",
    source: "read:get_portfolio_summary",
  },
  {
    capabilityId: "get_holdings",
    kind: "tool",
    status: "included",
    domain: "portfolio",
    toolName: "get_holdings",
    source: "read:get_holdings",
  },
  {
    capabilityId: "get_trade_history",
    kind: "tool",
    status: "included",
    domain: "market",
    toolName: "get_trade_history",
    source: "read:get_trade_history",
  },
  {
    capabilityId: "get_portfolio_history",
    kind: "tool",
    status: "included",
    domain: "portfolio",
    toolName: "get_portfolio_history",
    source: "read:get_portfolio_history",
  },
  {
    capabilityId: "search_players",
    kind: "tool",
    status: "included",
    domain: "players",
    toolName: "search_players",
    source: "storage:getPlayers",
  },
  {
    capabilityId: "get_player_detail",
    kind: "tool",
    status: "included",
    domain: "players",
    toolName: "get_player_detail",
    source: "read:get_player_detail",
  },
  {
    capabilityId: "get_player_stats",
    kind: "tool",
    status: "included",
    domain: "players",
    toolName: "get_player_stats",
    source: "read:get_player_stats",
  },
  {
    capabilityId: "get_player_recent_games",
    kind: "tool",
    status: "included",
    domain: "players",
    toolName: "get_player_recent_games",
    source: "read:get_player_recent_games",
  },
  {
    capabilityId: "get_player_financial_metrics",
    kind: "tool",
    status: "included",
    domain: "players",
    toolName: "get_player_financial_metrics",
    source: "read:get_player_financial_metrics",
  },
  {
    capabilityId: "get_player_shares_info",
    kind: "tool",
    status: "included",
    domain: "players",
    toolName: "get_player_shares_info",
    source: "read:get_player_shares_info",
  },
  {
    capabilityId: "get_market_scanners",
    kind: "tool",
    status: "included",
    domain: "market",
    toolName: "get_market_scanners",
    source: "storage:getFinancialMarketScanners",
  },
  {
    capabilityId: "get_games_today",
    kind: "tool",
    status: "included",
    domain: "games",
    toolName: "get_games_today",
    source: "storage:getDailyGamesBySport",
  },
  {
    capabilityId: "get_game_insights",
    kind: "tool",
    status: "included",
    domain: "games",
    toolName: "get_game_insights",
    source: "composed:game_insights",
  },
  {
    capabilityId: "get_news_digest",
    kind: "tool",
    status: "included",
    domain: "news",
    toolName: "get_news_digest",
    source: "job:compileUserDigest",
  },
  {
    capabilityId: "search_docs",
    kind: "tool",
    status: "included",
    domain: "docs",
    toolName: "search_docs",
    source: "docs:searchDocsArticles",
  },
  {
    capabilityId: "get_doc_article",
    kind: "tool",
    status: "included",
    domain: "docs",
    toolName: "get_doc_article",
    source: "docs:getDocsArticle",
  },
  {
    capabilityId: "run_hosted_research",
    kind: "tool",
    status: "included",
    domain: "research",
    toolName: "run_hosted_research",
    source: "read:get_hosted_research",
  },
  {
    capabilityId: "get_scout_status",
    kind: "tool",
    status: "included",
    domain: "scouting",
    toolName: "get_scout_status",
    source: "storage:getScoutStatus",
  },
  {
    capabilityId: "list_scout_assignments",
    kind: "tool",
    status: "included",
    domain: "scouting",
    toolName: "list_scout_assignments",
    source: "storage:getUserScoutAssignments",
  },
  {
    capabilityId: "get_scout_roster",
    kind: "tool",
    status: "included",
    domain: "scouting",
    toolName: "get_scout_roster",
    source: "storage:getScoutRoster",
  },
  {
    capabilityId: "list_watchlists",
    kind: "tool",
    status: "included",
    domain: "watchlists",
    toolName: "list_watchlists",
    source: "read:get_watchlists",
  },
  {
    capabilityId: "get_watchlist_items",
    kind: "tool",
    status: "included",
    domain: "watchlists",
    toolName: "get_watchlist_items",
    source: "read:get_watchlist_items",
  },
  {
    capabilityId: "list_player_watchlists",
    kind: "tool",
    status: "included",
    domain: "watchlists",
    toolName: "list_player_watchlists",
    source: "read:get_player_watchlists",
  },
  {
    capabilityId: "get_holding_multiplier_state",
    kind: "tool",
    status: "included",
    domain: "portfolio",
    toolName: "get_holding_multiplier_state",
    source: "read:get_holding_multiplier_state",
  },
  {
    capabilityId: "list_daily_boosts",
    kind: "tool",
    status: "included",
    domain: "boosts",
    toolName: "list_daily_boosts",
    source: "read:get_daily_boost_state",
  },
  {
    capabilityId: "list_daily_boost_eligible_players",
    kind: "tool",
    status: "included",
    domain: "boosts",
    toolName: "list_daily_boost_eligible_players",
    source: "read:get_daily_boost_eligibility",
  },
  {
    capabilityId: "list_daily_boost_history",
    kind: "tool",
    status: "included",
    domain: "boosts",
    toolName: "list_daily_boost_history",
    source: "read:get_daily_boost_history",
  },
  {
    capabilityId: "get_community_boost_state",
    kind: "tool",
    status: "included",
    domain: "community_boosts",
    toolName: "get_community_boost_state",
    source: "read:get_community_boost_state",
  },
  {
    capabilityId: "list_community_boost_history",
    kind: "tool",
    status: "included",
    domain: "community_boosts",
    toolName: "list_community_boost_history",
    source: "route:/api/community-boosts/history",
  },
  {
    capabilityId: "list_community_boost_eligible_players",
    kind: "tool",
    status: "included",
    domain: "community_boosts",
    toolName: "list_community_boost_eligible_players",
    source: "route:/api/community-boosts/eligible-players",
  },
  {
    capabilityId: "list_lp_positions",
    kind: "tool",
    status: "included",
    domain: "liquidity",
    toolName: "list_lp_positions",
    source: "read:get_lp_positions",
  },
  {
    capabilityId: "get_lp_position",
    kind: "tool",
    status: "included",
    domain: "liquidity",
    toolName: "get_lp_position",
    source: "read:get_lp_position",
  },
  {
    capabilityId: "list_lp_history",
    kind: "tool",
    status: "included",
    domain: "liquidity",
    toolName: "list_lp_history",
    source: "read:get_lp_history",
  },
  {
    capabilityId: "get_amm_pool_state",
    kind: "tool",
    status: "included",
    domain: "market",
    toolName: "get_amm_pool_state",
    source: "read:get_amm_pool_state",
  },
  {
    capabilityId: "get_trade_quote",
    kind: "tool",
    status: "included",
    domain: "market",
    toolName: "get_trade_quote",
    source: "read:get_amm_trade_quote",
  },
  {
    capabilityId: "get_lp_zap_quote",
    kind: "tool",
    status: "included",
    domain: "liquidity",
    toolName: "get_lp_zap_quote",
    source: "amm:getZapAddQuote",
  },
  {
    capabilityId: "list_schedules",
    kind: "tool",
    status: "included",
    domain: "schedules",
    toolName: "list_schedules",
    source: "read:get_user_schedules",
  },
  {
    capabilityId: "list_schedule_templates",
    kind: "tool",
    status: "included",
    domain: "schedules",
    toolName: "list_schedule_templates",
    source: "read:get_schedule_templates",
  },
  {
    capabilityId: "list_agent_threads",
    kind: "tool",
    status: "included",
    domain: "threads",
    toolName: "list_agent_threads",
    source: "thread:listAgentThreads",
  },
  {
    capabilityId: "get_thread_state",
    kind: "tool",
    status: "included",
    domain: "threads",
    toolName: "get_thread_state",
    source: "read:get_thread_state",
  },
  {
    capabilityId: "get_pending_action",
    kind: "tool",
    status: "included",
    domain: "threads",
    toolName: "get_pending_action",
    source: "read:get_pending_bundle",
  },
  {
    capabilityId: "stage_market_buy",
    kind: "tool",
    status: "included",
    domain: "market",
    toolName: "stage_market_buy",
    source: "plan:preview_pool_buy+thread",
  },
  {
    capabilityId: "stage_market_sell",
    kind: "tool",
    status: "included",
    domain: "market",
    toolName: "stage_market_sell",
    source: "plan:preview_pool_sell+thread",
  },
  {
    capabilityId: "stage_lp_add",
    kind: "tool",
    status: "included",
    domain: "liquidity",
    toolName: "stage_lp_add",
    source: "plan:preview_lp_add+thread",
  },
  {
    capabilityId: "stage_lp_add_optimal",
    kind: "tool",
    status: "included",
    domain: "liquidity",
    toolName: "stage_lp_add_optimal",
    source: "plan:preview_lp_add_optimal+thread",
  },
  {
    capabilityId: "stage_lp_zap_add",
    kind: "tool",
    status: "included",
    domain: "liquidity",
    toolName: "stage_lp_zap_add",
    source: "plan:preview_lp_zap+thread",
  },
  {
    capabilityId: "stage_lp_remove",
    kind: "tool",
    status: "included",
    domain: "liquidity",
    toolName: "stage_lp_remove",
    source: "plan:preview_lp_remove+thread",
  },
  {
    capabilityId: "stage_scout_assignment",
    kind: "tool",
    status: "included",
    domain: "scouting",
    toolName: "stage_scout_assignment",
    source: "plan:preview_scout_adjustment+thread",
  },
  {
    capabilityId: "stage_stack_shares",
    kind: "tool",
    status: "included",
    domain: "portfolio",
    toolName: "stage_stack_shares",
    source: "plan:preview_stack_shares+thread",
  },
  {
    capabilityId: "stage_daily_boost_assign",
    kind: "tool",
    status: "included",
    domain: "boosts",
    toolName: "stage_daily_boost_assign",
    source: "plan:preview_daily_boost_assign+thread",
  },
  {
    capabilityId: "stage_daily_boost_remove",
    kind: "tool",
    status: "included",
    domain: "boosts",
    toolName: "stage_daily_boost_remove",
    source: "plan:preview_daily_boost_remove+thread",
  },
  {
    capabilityId: "create_watchlist",
    kind: "tool",
    status: "included",
    domain: "watchlists",
    toolName: "create_watchlist",
    source: "action:create_watchlist",
  },
  {
    capabilityId: "update_watchlist",
    kind: "tool",
    status: "included",
    domain: "watchlists",
    toolName: "update_watchlist",
    source: "action:update_watchlist",
  },
  {
    capabilityId: "delete_watchlist",
    kind: "tool",
    status: "included",
    domain: "watchlists",
    toolName: "delete_watchlist",
    source: "action:delete_watchlist",
  },
  {
    capabilityId: "add_watchlist_player",
    kind: "tool",
    status: "included",
    domain: "watchlists",
    toolName: "add_watchlist_player",
    source: "action:add_watchlist_player",
  },
  {
    capabilityId: "remove_watchlist_player",
    kind: "tool",
    status: "included",
    domain: "watchlists",
    toolName: "remove_watchlist_player",
    source: "action:remove_watchlist_player",
  },
  {
    capabilityId: "stage_community_boost_create",
    kind: "tool",
    status: "included",
    domain: "community_boosts",
    toolName: "stage_community_boost_create",
    source: "plan:preview_community_boost_create+thread",
  },
  {
    capabilityId: "upsert_schedule",
    kind: "tool",
    status: "included",
    domain: "schedules",
    toolName: "upsert_schedule",
    source: "action:upsert_user_schedule",
  },
  {
    capabilityId: "delete_schedule",
    kind: "tool",
    status: "included",
    domain: "schedules",
    toolName: "delete_schedule",
    source: "action:delete_user_schedule",
  },
  {
    capabilityId: "create_agent_thread",
    kind: "tool",
    status: "included",
    domain: "threads",
    toolName: "create_agent_thread",
    source: "action:create_agent_thread",
  },
  {
    capabilityId: "send_agent_message",
    kind: "tool",
    status: "included",
    domain: "threads",
    toolName: "send_agent_message",
    source: "thread:sendAgentThreadMessage",
  },
  {
    capabilityId: "confirm_pending_action",
    kind: "tool",
    status: "included",
    domain: "threads",
    toolName: "confirm_pending_action",
    source: "thread:confirmAgentThread",
  },
  {
    capabilityId: "cancel_pending_action",
    kind: "tool",
    status: "included",
    domain: "threads",
    toolName: "cancel_pending_action",
    source: "thread:cancelAgentThread",
  },
  {
    capabilityId: "sportfolio://capabilities",
    kind: "resource",
    status: "included",
    domain: "docs",
    resourceUri: "sportfolio://capabilities",
    source: "mcp:static_resource",
  },
  {
    capabilityId: "sportfolio://docs/index",
    kind: "resource",
    status: "included",
    domain: "docs",
    resourceUri: "sportfolio://docs/index",
    source: "mcp:docs_resource",
  },
  {
    capabilityId: "sportfolio://action-surface",
    kind: "resource",
    status: "included",
    domain: "docs",
    resourceUri: "sportfolio://action-surface",
    source: "mcp:static_resource",
  },
  {
    capabilityId: "review_setup_prompt",
    kind: "prompt",
    status: "included",
    domain: "prompts",
    promptName: "review_setup",
    source: "mcp:prompt",
  },
  {
    capabilityId: "review_idle_cash_prompt",
    kind: "prompt",
    status: "included",
    domain: "prompts",
    promptName: "review_idle_cash",
    source: "mcp:prompt",
  },
  {
    capabilityId: "find_boost_candidates_prompt",
    kind: "prompt",
    status: "included",
    domain: "prompts",
    promptName: "find_boost_candidates",
    source: "mcp:prompt",
  },
  {
    capabilityId: "stage_trade_prompt",
    kind: "prompt",
    status: "included",
    domain: "prompts",
    promptName: "stage_trade",
    source: "mcp:prompt",
  },
];

export const EXCLUDED_GAMEPLAY_CAPABILITIES: GameplayCapabilityEntry[] = [
  {
    capabilityId: "premium_checkout_session",
    kind: "excluded",
    status: "excluded",
    domain: "billing",
    source: "/api/premium/checkout-session",
    notes: "Purchase flow is out of scope for MCP v1.",
  },
  {
    capabilityId: "community_checkout_session",
    kind: "excluded",
    status: "excluded",
    domain: "billing",
    source: "/api/community/checkout-session",
    notes: "Community share purchase flow is out of scope for MCP v1.",
  },
  {
    capabilityId: "checkout_finalize",
    kind: "excluded",
    status: "excluded",
    domain: "billing",
    source: "/api/checkout/finalize",
    notes: "Checkout finalization is out of scope for MCP v1.",
  },
  {
    capabilityId: "mobile_rewarded_scout_boost_session",
    kind: "excluded",
    status: "excluded",
    domain: "mobile",
    source: "/api/mobile/rewarded-scout-boost/session",
    notes: "Native mobile rewarded ad session bootstrap is out of scope for MCP v1.",
  },
  {
    capabilityId: "mobile_rewarded_scout_boost_session_status",
    kind: "excluded",
    status: "excluded",
    domain: "mobile",
    source: "/api/mobile/rewarded-scout-boost/session/:rewardSessionId/status",
    notes: "Native mobile rewarded ad verification polling is out of scope for MCP v1.",
  },
  {
    capabilityId: "mobile_rewarded_scout_boost_client_complete",
    kind: "excluded",
    status: "excluded",
    domain: "mobile",
    source: "/api/mobile/rewarded-scout-boost/session/:rewardSessionId/client-complete",
    notes: "Native mobile rewarded ad client completion is out of scope for MCP v1.",
  },
  {
    capabilityId: "admin_rewarded_scout_boost_session_debug",
    kind: "excluded",
    status: "excluded",
    domain: "admin",
    source: "/api/admin/rewarded-scout-boost/session/:rewardSessionId",
    notes: "Admin-only rewarded ad session diagnostics are out of scope for MCP v1.",
  },
  {
    capabilityId: "user_add_cash",
    kind: "excluded",
    status: "excluded",
    domain: "billing",
    source: "/api/user/add-cash",
    notes: "Funding flows are excluded from MCP v1.",
  },
  {
    capabilityId: "account_bootstrap_and_tokens",
    kind: "excluded",
    status: "excluded",
    domain: "account",
    source: "account/bootstrap/token-management",
    notes: "Bootstrap and token-management flows are web-only in v1.",
  },
  {
    capabilityId: "sms_linking_and_settings",
    kind: "excluded",
    status: "excluded",
    domain: "account",
    source: "sms/linking/settings",
    notes: "SMS linking and settings are excluded from gameplay parity.",
  },
  {
    capabilityId: "username_and_profile_image",
    kind: "excluded",
    status: "excluded",
    domain: "account",
    source: "profile/identity",
    notes: "Identity profile edits are excluded from gameplay parity.",
  },
  {
    capabilityId: "agent_profile_and_byok_settings",
    kind: "excluded",
    status: "excluded",
    domain: "account",
    source: "agent/profile/byok",
    notes: "Agent settings remain web-only in v1.",
  },
  {
    capabilityId: "admin_internal_routes",
    kind: "excluded",
    status: "excluded",
    domain: "admin",
    source: "admin/internal-only routes",
    notes: "Admin and internal routes must not be exposed via MCP.",
  },
];

export const INCLUDED_GAMEPLAY_TOOL_NAMES = INCLUDED_GAMEPLAY_CAPABILITIES.filter(
  (entry) => entry.kind === "tool" && entry.toolName,
).map((entry) => entry.toolName as string);

export const INCLUDED_GAMEPLAY_RESOURCE_URIS = INCLUDED_GAMEPLAY_CAPABILITIES.filter(
  (entry) => entry.kind === "resource" && entry.resourceUri,
).map((entry) => entry.resourceUri as string);

export const INCLUDED_GAMEPLAY_PROMPT_NAMES = INCLUDED_GAMEPLAY_CAPABILITIES.filter(
  (entry) => entry.kind === "prompt" && entry.promptName,
).map((entry) => entry.promptName as string);
